org: dylanm
app: aws-python-twitch-eventsub-to-discord
service: aws-python-twitch-eventsub-to-discord
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: python3.8

functions:
  webhook:
    handler: handler.webhook
    environment:
      DISCORD_WEBHOOK_URL: ${env:DISCORD_WEBHOOK_URL}
      DISCORD_ROLE_ID: ${env:DISCORD_ROLE_ID}
      TWITCH_USERNAME: ${env:TWITCH_USERNAME}
    events:
      - http:
          path: webhook
          method: POST
          cors: true


plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    slim: true
    useDownloadCache: true
    useStaticCache: true
